config/routes.rb
Rails.application.routes.draw do
  resources :working_hours, only: [:index]
  

  
  root to: 'working_hours#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/professional.rb
class Professional < ApplicationRecord
  has_many :working_hours, dependent: :destroy
end

app/models/working_hour.rb
class WorkingHour < ApplicationRecord
  belongs_to :professional
end
rails generate migration AddOffDayToWorkingHours off_day:boolean

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    after_action :allow_iframe

  private

  def allow_iframe
    response.headers.except! 'X-Frame-Options'
  end
end
rails generate controller Professionals
rails generate controller WorkingHours

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
     # nothing to do here
  end
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  before_action :set_professional, only: [:show, :edit, :update, :destroy]

  def index
    @professionals = Professional.all
  end

  def show
  end

  def new
    @professional = Professional.new
  end

  def edit
  end

  def create
    @professional = Professional.new(professional_params)

    if @professional.save
      redirect_to @professional, notice: 'Professional was successfully created.'
    else
      render :new
    end
  end

  def update
    if @professional.update(professional_params)
      redirect_to @professional, notice: 'Professional was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @professional.destroy
    redirect_to professionals_url, notice: 'Professional was successfully destroyed.'
  end

  private
    def set_professional
      @professional = Professional.find(params[:id])
    end

    def professional_params
      params.require(:professional).permit(:name)
    end
end

app/controllers/working_hours_controller.rb
class WorkingHoursController < ApplicationController
  before_action :authenticate_user! # Add authentication logic if using Devise
  
  def index
    @working_hours = WorkingHour.all
  end
  
  def new
    @working_hour = WorkingHour.new
  end
  
  def create
    @working_hour = WorkingHour.new(working_hour_params)
    
    if @working_hour.save
      redirect_to working_hours_path, notice: 'Working hour was successfully created.'
    else
      render :new
    end
  end
  
  def edit
    @working_hour = WorkingHour.find(params[:id])
  end
  
  def update
    @working_hour = WorkingHour.find(params[:id])
    
    if @working_hour.update(working_hour_params)
      redirect_to working_hours_path, notice: 'Working hour was successfully updated.'
    else
      render :edit
    end
  end
  
  private
  
  def working_hour_params
    params.require(:working_hour).permit(:day, :start_time, :end_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workspace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Working Hours</h1>

<% @working_hours.each do |working_hour| %>
  <p>
    <strong><%= working_hour.day %>:</strong>
    <%= working_hour.start_time.strftime('%H:%M') %> - <%= working_hour.end_time.strftime('%H:%M') %>
    <%= link_to 'Edit', edit_working_hour_path(working_hour) %>
  </p>
<% end %>

<%= link_to 'Add Working Hour', new_working_hour_path %>
<h1>Working Hours</h1>

<% @working_hours.each do |working_hour| %>
  <p>
    <strong><%= working_hour.day %>:</strong>
    <%= working_hour.start_time.strftime('%H:%M') %> - <%= working_hour.end_time.strftime('%H:%M') %>
  </p>
<% end %>

app/views/working_hours/index.html.erb
<h1>Working Hours</h1>

<% @working_hours.each do |working_hour| %>
  <p>
    <strong><%= working_hour.day %>:</strong>
    <%= working_hour.start_time.strftime('%H:%M') %> - <%= working_hour.end_time.strftime('%H:%M') %>
  </p>
<% end %>